helmetologist/cart/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
from django.contrib.auth.views import LogoutView
urlpatterns = [
        
    path('cart/', cart_show, name='cart_show'),
    path('add_to_cart/<int:product_id>',add_to_cart,name='add_to_cart'),
    path('update_item/', updateItem, name='update_item'),
    path('update_wishlist/', updateWishlist, name='update_wishlist'),
    path('update_cart_item/', updateCartItem, name='update_cart_item'),
    path('delete_from_cart/<str:product_id>/', delete_from_cart, name='delete_from_cart'),
    path('checkout/', cash_on_delivery, name='checkout'),
    path('checkout_view/', checkout_view, name='checkout_view'),
    # path('payment_success/', payment_success, name='payment_success'),
  
    path('checkout_success/<int:order_id>/', checkout_success, name='checkout_success'),
    path('wishlist/',wishlist,name='wishlist'),
    path('add_to_wishlist/<int:product_id>',add_to_wishlist,name='add_to_wishlist'),
    path('remove_from_wishlist/<int:product_id>',remove_from_wishlist,name='remove_from_wishlist'),
    path('wishlist_to_cart/<int:product_id>',wishlist_to_cart,name='wishlist_to_cart'),
    path('admincoupon/', admincoupon, name='admincoupon'),
    path('coupon_inactive/<int:coupon_id>',coupon_inactive,name='coupon_inactive'),
    path('add_coupon/', add_coupon, name='add_coupon'),
    path('checkout_add_address/',checkout_add_address,name='checkout_add_address'),
    path('edit_coupon/<int:coupon_id>',edit_coupon, name='edit_coupon'),
    
#  razorpay
    path('create_razorpay_order/', create_razorpay_order, name='create_razorpay_order'),
    path('verify_razorpay_payment/', verify_razorpay_payment, name='verify_razorpay_payment'),
    path('handle_payment_failure/', handle_payment_failure, name='handle_payment_failure'),
    
    path('process-wallet-payment/', process_wallet_payment, name='process_wallet_payment'),
   

    # path('clear_cart/<int:cart_id>',clear_cart,name='clear_cart'),
    ]

helmetologist/offer/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
from django.contrib.auth.views import LogoutView

urlpatterns = [       
    path('adminoffers/', adminoffers , name='adminoffers'),
    path('add_offer/', add_offer, name='add_offer'),
    path('offer_inactive/<int:offer_id>',offer_inactive,name='offer_inactive'),
    path('edit_offer/<int:offer_id>', edit_offer, name='edit_offer'),
    path('delete_offer/<int:offer_id>', delete_offer, name='delete_offer'),
    # path('get_offer/<int:offer_id>/', get_offer, name='get_offer'),
    ]

helmetologist/offer/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils import timezone
from products.models import Products
from category.models import Category
from .validators import validate_offer_data
# Create your models here.


class Offer(models.Model):
    
    OFFER_TYPES = (
        ('product', 'Product'),
        ('category', 'Category'),
    )
    
    name = models.CharField(max_length=100)
    discount_percentage = models.DecimalField(
        max_digits=5, 
        decimal_places=2, 
        validators=[MinValueValidator(0), MaxValueValidator(100)]
    )
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    is_active = models.BooleanField(default=True)
    offer_type = models.CharField(max_length=20, choices=OFFER_TYPES, default='product')

    def __str__(self):
        return self.name

    def is_valid(self):
        now = timezone.now()
        return self.is_active and self.start_date <= now <= self.end_date
    

    
    def update_active_status(self):
        if not self.is_valid() :
            self.is_active = False
            self.save()

helmetologist/offer/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required,user_passes_test
from django.contrib import messages
from django.views.decorators.cache import never_cache
from user_account.models import User
from django.http import JsonResponse
from django.views.decorators.http import require_POST




from django.shortcuts import render, redirect, get_object_or_404

from django.views.decorators.http import require_POST
from .models import Offer, Products,Category
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
import json
from django.views.decorators.http import require_http_methods
from django.contrib.auth.decorators import user_passes_test
from .validators import validate_offer_data
from django.core.exceptions import ValidationError
# Create your views here.

def is_superuser(user):
    return user.is_superuser





@login_required(login_url='/adminlogin/')
@user_passes_test(is_superuser)
def adminoffers(request):
    
    offers = Offer.objects.all()   
    
    context = {
        'offers' : offers, 
    }
    return render(request,'adminoffer.html',context)

@login_required(login_url='/adminlogin/')
@user_passes_test(is_superuser)
def add_offer(request):
    errors = []
    if request.method == 'POST':
        name = request.POST.get('name')
        start_date = request.POST.get('start_date')
        end_date = request.POST.get('end_date')
        discount_percentage = request.POST.get('discount_percentage')
        is_active = request.POST.get('is_active') == 'True'
        offer_type = request.POST.get('offer_type')

        try:
            validate_offer_data(name, start_date, end_date, discount_percentage)

            Offer.objects.create(
                name=name,
                start_date=start_date,
                end_date=end_date,
                discount_percentage=discount_percentage,
                is_active=is_active,
                offer_type=offer_type
            )
            return redirect('adminoffers')
        except ValidationError as e:
            errors = e.messages

    return render(request, 'add_offer.html', {'messages': errors})
    


@login_required(login_url='/adminlogin/')
@user_passes_test(is_superuser)
@csrf_exempt
def edit_offer(request, offer_id):
    offer = get_object_or_404(Offer, id=offer_id)
    errors = []

    if request.method == 'POST':
        name = request.POST.get('name')
        start_date = request.POST.get('start_date')
        end_date = request.POST.get('end_date')
        discount_percentage = request.POST.get('discount_percentage')
        is_active = request.POST.get('is_active') == 'True'
        offer_type = request.POST.get('offer_type')

        try:
            validate_offer_data(name, start_date, end_date, discount_percentage)
            
            
            offer.name = name
            offer.start_date = start_date
            offer.end_date = end_date
            offer.discount_percentage = discount_percentage
            offer.is_active = is_active
            offer.offer_type = offer_type

            offer.save()

            messages.success(request, 'Offer has been updated successfully.')
            return redirect('adminoffers')
        except ValidationError as e:
            errors = e.messages

    return render(request, 'edit_offer.html', {'offer': offer, 'messages': errors})

@login_required(login_url='/adminlogin/')
@user_passes_test(is_superuser)
@csrf_exempt
def delete_offer(request, offer_id):
    # Fetch the offer or return a 404 if not found
    offer = get_object_or_404(Offer, id=offer_id)

    # Fetch and update related products
    products = Products.objects.filter(is_offer_applied=True,offer_id = offer_id )
    
    for product in products:
        # Reset offer-related fields
        product.discount_percentage = None
        product.is_offer_applied = False
        product.validate_offerdate = None
        product.discounted_price = None
        product.save(update_fields=['discount_percentage', 'is_offer_applied', 'validate_offerdate', 'discounted_price'])

    # Delete the offer
    offer.delete()

    # Redirect with a success message
    messages.success(request, "Offer deleted successfully.")
    return redirect('adminoffers')

@require_POST
@login_required(login_url='/adminlogin/')
@user_passes_test(is_superuser)    
def offer_inactive(request, offer_id):
    offer = get_object_or_404(Offer, id=offer_id)
    offer.is_active = not offer.is_active
    products = Products.objects.filter(is_offer_applied=True,offer_id = offer_id )
    
    for product in products:
        # Reset offer-related fields
        product.discount_percentage = None
        product.is_offer_applied = False
        product.validate_offerdate = None
        product.discounted_price = None
        product.save(update_fields=['discount_percentage', 'is_offer_applied', 'validate_offerdate', 'discounted_price'])

    offer.save()
    return redirect('adminoffers')

helmetologist/offer/templates/add_offer.html
{% extends "adminbase.html" %}
{% load static %}
{% block title %}Add Coupon{% endblock %}

{% block extra_styles %}
<!-- Custom style CSS -->

<link href="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.12/cropper.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.13/cropper.min.css">
{% endblock %}

{% block content %}
<section class="section">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h4>Add New Coupon</h4>
                </div>
                <!-- Alert Messages -->
                {% if messages %}
                {% for message in messages %}
                <div class="alert alert-danger d-flex align-items-center" role="alert">
                    <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:">
                        <use xlink:href="#exclamation-triangle-fill"/>
                    </svg>
                    <div>
                        {{ message }}
                    </div>
                </div>
                {% endfor %}
                {% endif %}

                <div class="card-body">
                    <div id="addProductsFormContainer">
                       
                        <form id="addProductsForm" action="{% url 'add_offer' %}" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="title">Offer name</label>
                                <input type="text" class="form-control" id="name" name="name" required>
                            </div>
                            <div class="form-group">
                                <label for="start_date">Start Date</label>
                                <input type="date" class="form-control" id="start_date" name="start_date" required>
                            </div>
                            <div class="form-group">
                                <label for="end_date">End Date</label>
                                <input type="date" class="form-control" id="end_date" name="end_date" required>
                            </div>
                            <div class="form-group">
                                <label for="discount_percentage">Discount Percentage</label>
                                <input type="number" step="0.01" class="form-control" id="discount_percentage" name="discount_percentage" required>
                            </div>
                            <div class="form-group">
                                <select class="form-control" id="isActive" name="is_active">
                                    <option value="False">Inactive</option>
                                    <option value="True">Active</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="offerType" class="form-label">Offer Type</label>
                                    <select class="form-control" id="offerType" name="offer_type">
                                        <option value="product">Product</option>
                                        <option value="category">Category</option>
                                    </select>
                            </div>
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </form>
                        
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

     
    

{% endblock %}

{% block scripts %}



                
<script src="{% static 'adminassets/bundles/datatables/datatables.min.js' %}"></script>
<script src="{% static 'adminassets/bundles/datatables/DataTables-1.10.16/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'adminassets/js/page/datatables.js' %}"></script>
<script src="{% static 'adminassets/js/scripts.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

  
{% endblock %}

helmetologist/offer/templates/adminoffer.html
{% extends "adminbase.html" %}
{% load static %}
{% block title %}Admin-order details{% endblock %}

<!-- this block custom styles eg :
<link rel="stylesheet" href="{% static 'css/custom_style.css' %}"> -->
{% block extra_styles %}



{% endblock %}
<!-- end styles -->

<!-- main content start -->
{% block content %}

<!-- Main Content -->

<section class="section">
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header">
          <h4>Table of  offer details</h4>
           <a href="{% url 'add_offer' %}" class="btn btn-primary">Add Offer</a>
        </div>
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-striped table-hover" id="save-stage" style="width:100%;">
              <thead>
                <tr>
                  <th>Offer Name</th>
                  <th>Valid Period</th>
                  <th>Discount percentage</th>
                  <th>Type</th>
                  <th>Status</th>
                  <th>Edit</th>
                  <th>Action</th>
                  
    
                  
                </tr>
              </thead>
              <tbody>
                {% for offer in offers %}
                <tr data="">
                  <td>{{ offer.name }}</td>
                  <td>{{offer.start_date|date:"Y-m-d" }} - {{offer.end_date|date:"Y-m-d" }}</td>
                  <td>{{ offer.discount_percentage }}%</td>
                  <td>{{ offer.get_offer_type_display }}</td>
                  <td>
                    {% if  offer.is_active %}  
                    <form method="POST"
                        action="{% url 'offer_inactive' offer.id %}"
                        style="display:inline;">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-success">Active</button>
                    </form>
                    {% else %}
                    <form method="POST"
                        action="{% url 'offer_inactive' offer.id %}"
                        style="display:inline;">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger">Deactive</button>
                    </form>
                    {% endif %}
                  </td>
                  <td><a href="{% url 'edit_offer' offer.id %}" class="edit_coupon btn btn-primary">Edit</a>
                  </td>
                  <td><a href="{% url 'delete_offer' offer.id %}" class="delete_coupon btn btn-warning">Delete</a></td>

                </tr>
                {% endfor %}


               
                
              </tbody>
              {% if messages %}
                {% for message in messages %}
                <div class="alert alert-danger d-flex align-items-center" role="alert">
                    <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:">
                        <use xlink:href="#exclamation-triangle-fill"/>
                    </svg>
                    <div>
                        {{ message }}
                    </div>
                </div>
                {% endfor %}
                {% endif %}
            </table>
            

          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}
<!-- main content start -->

{% block scripts %}

<script src="{% static 'adminassets/bundles/datatables/datatables.min.js' %}"></script>
<script src="{% static 'adminassets/bundles/jquery-ui/jquery-ui.min.js' %}"></script>
<script src="{% static 'adminassets/js/page/datatables.js' %}"></script>

<script>
  
</script>
{% endblock %}




 

helmetologist/offer/templates/edit_offer.html
{% extends "adminbase.html" %}
{% load static %}
{% block title %}Add Coupon{% endblock %}

{% block extra_styles %}
<!-- Custom style CSS -->

<link href="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.12/cropper.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.13/cropper.min.css">
{% endblock %}

{% block content %}
<section class="section">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h4>Edit offer : {{offer.name}}</h4>
                </div>
                <!-- Alert Messages -->
                {% if messages %}
                {% for message in messages %}
                <div class="alert alert-danger d-flex align-items-center" role="alert">
                    <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:">
                        <use xlink:href="#exclamation-triangle-fill"/>
                    </svg>
                    <div>
                        {{ message }}
                    </div>
                </div>
                {% endfor %}
                {% endif %}

                <div class="card-body">
                    <div id="addProductsFormContainer">
                       
                        <form id="addProductsForm" action="{% url 'edit_offer' offer.id %}" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="title">Offer name</label>
                                <input type="text" class="form-control" id="name" name="name" value="{{ offer.name }}" required>
                            </div>
                            <div class="form-group">
                                <label for="start_date">Start Date</label>
                                <input type="date" class="form-control" id="start_date" name="start_date" value="{{ offer.start_date|date:'Y-m-d' }}" required>
                            </div>
                            <div class="form-group">
                                <label for="end_date">End Date</label>
                                <input type="date" class="form-control" id="end_date" name="end_date" value="{{ offer.end_date|date:'Y-m-d' }}" required>
                            </div>
                            <div class="form-group">
                                <label for="discount_percentage">Discount Percentage</label>
                                <input type="number" step="0.01" class="form-control" id="discount_percentage" name="discount_percentage" value="{{offer.discount_percentage}}" required>
                            </div>
                            <div class="form-group">
                                <label for="isActive" class="form-label">Status</label>
                                <select class="form-control" id="isActive" name="is_active">
                                    <option value="True" {% if offer.is_active %}selected{% endif %}>Active</option>
                                    <option value="False" {% if not offer.is_active %}selected{% endif %}>Inactive</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="offerType" class="form-label">Offer Type</label>
                                <select class="form-control" id="offerType" name="offer_type">
                                    <option value="product" {% if offer.offer_type == "product" %} selected {% endif %}>Product</option>
                                    <option value="category" {% if offer.offer_type == "category" %} selected {% endif %}>Category</option>
                                </select>
                            </div>
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block scripts %}



                
<script src="{% static 'adminassets/bundles/datatables/datatables.min.js' %}"></script>
<script src="{% static 'adminassets/bundles/datatables/DataTables-1.10.16/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'adminassets/js/page/datatables.js' %}"></script>
<script src="{% static 'adminassets/js/scripts.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

  
{% endblock %}